add images fork, clone, new branch
narze/hacktoberfest_ez pull request #15
Opened 2019-10-19 09:34 UTC by jakapatb

images commit, push, create pull request will comming next PR

2019-10-19 09:42 UTC, narze commented on README.md
> +### Folk
`Fork` 😄

2019-10-19 09:42 UTC, narze commented on README.md
> +
```suggestion
```

2019-10-19 09:45 UTC, narze commented
Nice image btw 👍

2019-10-19 10:05 UTC, narze requested changes
^

2019-10-22 03:47 UTC, narze commented
@jakapatb

2019-10-23 03:40 UTC, jakapatb reviewed
ผมยังไม่เขาใจระบบมันมาก อันนี้คือต้องทำอะไรต่ออะครับ

2019-10-23 10:46 UTC, narze approved these changes
Thanks!

2019-10-23 10:46 UTC, merged